-- Your SQL goes here
CREATE TYPE CargoType AS ENUM (
    'wood', 'wool', 'rum'
);

CREATE TABLE cargo_info (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  name CargoType NOT NULL,
  weight INTEGER NOT NULL,
  base_value INTEGER NOT NULL
);
