-- Your SQL goes here
CREATE TABLE ship_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  name varchar NOT NULL,
  speed INTEGER NOT NULL,
  max_cargo_size INTEGER NOT NULL,
  max_crew_size INTEGER NOT NULL,
  cost INTEGER NOT NULL
);
